import { canvas } from '../core/dom.js'
import { WORLD_WIDTH, WORLD_HEIGHT, zoomLevels } from '../config/constants.js'

export const zoomState = {
  index: 1,
  zoom: zoomLevels[1],
  viewWidth: canvas.width / zoomLevels[1],
  viewHeight: canvas.height / zoomLevels[1],
}

export const state = {
  running: false,
  paused: false,
  lastTime: 0,
  elapsed: 0,
  waveDuration: 30,
  nextBossWave: 5,
  pendingLevels: 0,
  pendingStatUps: 0,
  pendingRelicRarities: [],
}

export const input = {
  up: false,
  down: false,
  left: false,
  right: false,
  mouseActive: false,
  mouseX: 0,
  mouseY: 0,
}

export const player = {
  x: WORLD_WIDTH / 2,
  y: WORLD_HEIGHT / 2,
  r: 12,
  speed: 180,
  isMoving: false,
  maxHp: 100,
  hp: 100,
  damage: 18,
  fireRate: 1.2,
  bulletSpeed: 420,
  xp: 0,
  level: 1,
  nextXp: 20,
  pickupRadius: 30,
  pulseCooldown: 4.5,
  pulseRadius: 120,
  pulseDamage: 28,
  pulseKnockback: 320,
  pulseUnlocked: false,
  novaCooldown: 2.6,
  novaRadius: 70,
  novaDamage: 14,
  novaKnockback: 220,
  novaUnlocked: false,
  bladeCount: 2,
  bladeRadius: 34,
  bladeSpeed: 2.4,
  bladeDamage: 14,
  bladeHitCooldown: 0.35,
  bladeSize: 22,
  bladeAngle: 0,
  bladesUnlocked: false,
  frostFireRate: 0.9,
  frostDamage: 10,
  frostSpeed: 360,
  frostPierce: 2,
  frostShots: 2,
  frostUnlocked: false,
  chainCooldown: 1.6,
  chainDamage: 12,
  chainRange: 120,
  chainCount: 2,
  chainUnlocked: false,
  starfallCooldown: 3.4,
  starfallCount: 8,
  starfallDamage: 10,
  starfallSpeed: 280,
  starfallLife: 0.9,
  starfallUnlocked: false,
  mineCooldown: 5.5,
  mineDamage: 22,
  mineRadius: 54,
  mineArmTime: 0.35,
  mineMaxActive: 2,
  mineLifetime: 8,
  mineUnlocked: false,
  trailSpawnInterval: 0.3,
  trailPatchLife: 1.2,
  trailRadius: 20,
  trailDps: 14,
  trailMaxPatches: 24,
  trailUnlocked: false,
  vortexCooldown: 7,
  vortexDuration: 2.2,
  vortexRadius: 120,
  vortexPull: 260,
  vortexDps: 9,
  vortexUnlocked: false,
  orbCount: 1,
  orbRadius: 60,
  orbSpeed: 1.2,
  orbDamage: 8,
  orbHitCooldown: 0.6,
  orbAngle: 0,
  orbUnlocked: false,
  upgrades: {},
}

export const entities = {
  bullets: [],
  enemies: [],
  orbs: [],
  mines: [],
  trails: [],
  vortexes: [],
  relics: [],
  healthPacks: [],
  pulses: [],
  particles: [],
  chainArcs: [],
}

export const orbitCache = {
  blades: [],
  solars: [],
}

export const timers = {
  shoot: 0,
  starfall: 0,
  spawn: 0,
  mines: 0,
  trail: 0,
  vortex: 0,
  pulse: 0,
  nova: 0,
  frost: 0,
  chain: 0,
  relic: 0,
}
